apiVersion: apps/v1
kind: Deployment
metadata:
  name: blood-bank-deployment
  labels:
    app.kubernetes.io/name: blood-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blood-bank
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blood-bank
    spec:
      containers:
      - name: blood-bank-image
        image: santogiovanni/blood_bank:v2
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "200Mi"
        ports:
        - containerPort: 8081
  
---
apiVersion: v1
kind: Service
metadata:
  name: blood-bank-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: blood-bank
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 81
      targetPort: 8081
      nodePort: 31001
