apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-deployment
  labels:
    app.kubernetes.io/name: hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hospital
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hospital
    spec:
      containers:
      - name: hospital-image
        image: santogiovanni/hospital:v2
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "200Mi"
        ports:
        - containerPort: 8082
        env:
        - name: BLOOD_BANK_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: application-context
              key: blood_bank_host
        - name: BLOOD_BANK_PORT
          valueFrom:
            configMapKeyRef:
              name: application-context
              key: blood_bank_port
    
---
apiVersion: v1
kind: Service
metadata:
  name: hospital-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: hospital
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 82
      targetPort: 8082
      nodePort: 31002
